### ISSUE TITLE
启动gateaway失败

### ISSUE THREAD

**Issue by pullwindyuan** [7040210/SuperBoot#4]
多处提示：
nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'Snowflake.workerId' in value "${Snowflake.workerId}；

**Comment by pullwindyuan** [comment]
org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.cloud.netflix.zuul.ZuulProxyAutoConfiguration': Unsatisfied dependency expressed through field 'errorController'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestErrorController': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pub_Tools': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'Snowflake.workerId' in value "${Snowflake.workerId}"

**Comment by pullwindyuan** [comment]
再次启动又没问题了。是不是因为其他依赖服务没启动。
我对老大的这个项目非常感兴趣，希望能应用到我们现在生产项目中，不知道能不能提供更多的帮助信息，尤其是服务部署和实战指南。我们也能贡献代码。

**Comment by 7040210** [comment]
${Snowflake.workerId} 是配置文件里的一个参数用于生成分布式ID使用
