### ISSUE TITLE
redis问题

### ISSUE THREAD

**Issue by pullwindyuan** [7040210/SuperBoot#5]
你好，在启动注册中心过程中提示：org.springframework.data.redis.ClusterStateFailureException: Could not retrieve cluster information. CLUSTER NODES returned with error.
但是我们没有找到哪里有相关的配置redis的地方，是怎么回事呢，还有就是工程中好像还使用了mongoDBd,但是也是没有找到相关的配置，只看到了依赖。

**Comment by 7040210** [comment]
MongoDB使用默认配置了，如果IP与端口不一致在配置文件修改，配置的东西是使用配置中心获取的，具体配置中心实现方式 可参考相关文档说明
